set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
set(GIT_EXECUTABLE "/usr/bin/git")
set(Subversion_SVN_EXECUTABLE "/usr/bin/svn")
set(CMAKE_MAKE_PROGRAM "/usr/bin/make")
set(CMAKE_C_COMPILER "/usr/bin/cc")
set(CMAKE_CXX_COMPILER "/usr/bin/c++")
set(BUILD_TESTING "ON")
set(RUN_CTEST_SUBMIT "TRUE")
set(EXTENSION_BUILD_OPTIONS_STRING "64bits-Qt4.8")
set(EXTENSION_COMPILER "g++")
set(EXTENSION_NAME "AnomalousFiltersExtension")
set(EXTENSION_CATEGORY "Filtering.Anomalous Filters")
set(EXTENSION_STATUS "")
set(EXTENSION_ICONURL "http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/AnomalousFiltersExtension.png")
set(EXTENSION_CONTRIBUTORS "Antonio Carlos Senra Filho (University of Sao Paulo), Luiz Otavio Murta Junior (University of Sao Paulo)")
set(EXTENSION_DESCRIPTION "This is an example of a simple extension")
set(EXTENSION_HOMEPAGE "http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/AnomalousFilters")
set(EXTENSION_SCREENSHOTURLS "http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/Screenshots/1.png")
set(EXTENSION_SOURCE_DIR "/home/antonio/Documents/CSIM-Toolkits/Slicer/CLI/AnomalousFiltersExtension")
set(EXTENSION_SUPERBUILD_BINARY_DIR "/home/antonio/Documents/CSIM-Toolkits/Slicer/CLI/AnomalousFiltersExtension-build")
set(EXTENSION_BUILD_SUBDIRECTORY ".")
set(EXTENSION_ENABLED "1")
set(EXTENSION_DEPENDS "NA")
set(Slicer_CMAKE_DIR "/home/antonio/Slicer-Git/Slicer/CMake")
set(Slicer_DIR "/home/antonio/Slicer-Git/Slicer-SuperBuild-Debug/Slicer-build")
set(Slicer_EXTENSIONS_TRACK_QUALIFIER "master")
set(Slicer_WC_REVISION "23737")
set(MIDAS_PACKAGE_URL "http://slicer.kitware.com/midas3")
set(MIDAS_PACKAGE_EMAIL "YOUR-MIDAS-LOGIN-NOTFOUND")
set(MIDAS_PACKAGE_API_KEY "YOUR-MIDAS-APIKEY-NOTFOUND")
set(NA_DIR "")
set(RUN_CTEST_CONFIGURE "TRUE")
set(RUN_CTEST_BUILD "TRUE")
set(RUN_CTEST_TEST "TRUE")
set(RUN_CTEST_PACKAGES "TRUE")
set(RUN_CTEST_UPLOAD "FALSE")