# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "TGZ")
SET(CPACK_INSTALL_CMAKE_PROJECTS "/home/antonio/Documents/CSIM-Toolkits/Slicer/CLI/AnomalousFiltersExtension-build;AnomalousFiltersExtension;ALL;/")
SET(CPACK_INSTALL_PREFIX "/usr/local")
SET(CPACK_MODULE_PATH "/home/antonio/Slicer-Git/Slicer-SuperBuild-Debug/SlicerExecutionModel-build/CMake;/home/antonio/Slicer-Git/Slicer-SuperBuild-Debug/SlicerExecutionModel-build/CMake;/home/antonio/Slicer-Git/Slicer-SuperBuild-Debug/SlicerExecutionModel-build/CMake;/home/antonio/Slicer-Git/Slicer-SuperBuild-Debug/VTKv6/CMake;/home/antonio/Slicer-Git/Slicer-SuperBuild-Debug/ITKv4/Modules/ThirdParty/DCMTK/CMake;/home/antonio/Slicer-Git/Slicer-SuperBuild-Debug/CTK/Utilities/CMake;/home/antonio/Slicer-Git/Slicer-SuperBuild-Debug/CTK/CMake;/home/antonio/Slicer-Git/Slicer-SuperBuild-Debug/CTK/Utilities/CMake;/home/antonio/Slicer-Git/Slicer/CMake;/home/antonio/Slicer-Git/Slicer/Extensions/CMake;/home/antonio/Slicer-Git/Slicer-SuperBuild-Debug/VTKv6/CMake")
SET(CPACK_MONOLITHIC_INSTALL "ON")
SET(CPACK_NSIS_DISPLAY_NAME "AnomalousFiltersExtension 0.1.1")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_MODIFY_PATH "OFF")
SET(CPACK_NSIS_PACKAGE_NAME "AnomalousFiltersExtension 0.1.1")
SET(CPACK_OUTPUT_CONFIG_FILE "/home/antonio/Documents/CSIM-Toolkits/Slicer/CLI/AnomalousFiltersExtension-build/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/home/antonio/Slicer-Git/Slicer/README.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "This is an example of a simple extension")
SET(CPACK_PACKAGE_FILE_NAME "23737-linux-amd64-AnomalousFiltersExtension-gitb284fe2-2015-03-03")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "AnomalousFiltersExtension 0.1.1")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "AnomalousFiltersExtension 0.1.1")
SET(CPACK_PACKAGE_NAME "AnomalousFiltersExtension")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "NA-MIC")
SET(CPACK_PACKAGE_VERSION "0.1.1")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "1")
SET(CPACK_RESOURCE_FILE_LICENSE "/home/antonio/Slicer-Git/Slicer/License.txt")
SET(CPACK_RESOURCE_FILE_README "/usr/local/share/cmake-3.0/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/usr/local/share/cmake-3.0/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TGZ")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/antonio/Documents/CSIM-Toolkits/Slicer/CLI/AnomalousFiltersExtension-build/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_TBZ2 "OFF")
SET(CPACK_SOURCE_TGZ "ON")
SET(CPACK_SOURCE_TZ "OFF")
SET(CPACK_SOURCE_ZIP "OFF")
SET(CPACK_SYSTEM_NAME "Linux")
SET(CPACK_TOPLEVEL_TAG "Linux")
SET(CPACK_WIX_SIZEOF_VOID_P "8")
